# This file was generated by GoReleaser. DO NOT EDIT.
cask "ent" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "958028fe9940ba0cc244777f47e44c4a92e1853665cc8ff3ca4358455078cd48"
      url "https://github.com/AWDDude/ent/releases/download/v#{version}/ent_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "29d8ade44478489fc702893dbefff18f9cd9b312f5e46a6e7cd521419e8023c4"
      url "https://github.com/AWDDude/ent/releases/download/v#{version}/ent_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ef33d00b5c39cc6700e92a89750a7a82c5f0e93298645d461c01558ab2e0620c"
      url "https://github.com/AWDDude/ent/releases/download/v#{version}/ent_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6548226eb2ee530282424c8bc2ee8fa4d7e0572e7c858e3b32ccaaacdb9721a4"
      url "https://github.com/AWDDude/ent/releases/download/v#{version}/ent_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ent"
  desc "A project manager CLI — organise and navigate your projects tree"
  homepage "https://github.com/AWDDude/ent"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ent"

  postflight do
    system_command "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "#{staged_path}/ent"]
  end

  # No zap stanza required

  caveats <<~EOS
    Add shell integration to your rc file:

      # zsh (~/.zshrc)
      eval "$(ent completion zsh)"

      # bash (~/.bashrc)
      eval "$(ent completion bash)"

      # fish (~/.config/fish/config.fish)
      ent completion fish | source

      # PowerShell ($PROFILE)
      ent completion powershell | Out-String | Invoke-Expression
  EOS
end
