# This file was generated by GoReleaser. DO NOT EDIT.
cask "ent" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "692dcf5fbbf30b2ac9564288aa83c7019f3968b1db0233bbb79fa41f4492b03c"
      url "https://github.com/AWDDude/ent/releases/download/v#{version}/ent_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "122e0165e5cadf0cb72dc968cb8e5e5aa92bf6c69f4fd93c96463a3c0f8b74be"
      url "https://github.com/AWDDude/ent/releases/download/v#{version}/ent_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f452438ff26dc492a2b7f997dd3966a58ebecb7783f74eaf02207dbe8d65754c"
      url "https://github.com/AWDDude/ent/releases/download/v#{version}/ent_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c6275320c2cf9f64ff4356669453e23488103a7a1c64d080e07e8b10b4438ca4"
      url "https://github.com/AWDDude/ent/releases/download/v#{version}/ent_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ent"
  desc "A project manager CLI — organise and navigate your projects tree"
  homepage "https://github.com/AWDDude/ent"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ent"

  postflight do
    system_command "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "#{staged_path}/ent"]
  end

  # No zap stanza required

  caveats <<~EOS
    Add shell integration to your rc file:

      # zsh (~/.zshrc)
      eval "$(ent completion zsh)"

      # bash (~/.bashrc)
      eval "$(ent completion bash)"

      # fish (~/.config/fish/config.fish)
      ent completion fish | source

      # PowerShell ($PROFILE)
      ent completion powershell | Out-String | Invoke-Expression
  EOS
end
