# This file was generated by GoReleaser. DO NOT EDIT.
cask "ent" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "3c8019155d9800b2e3acf0e2f7d16ad7724738871c85abc05001092f7d45b1bd"
      url "https://github.com/AWDDude/ent/releases/download/v#{version}/ent_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "64fc73fcdaeab62537cc23568743d752595c2a56c12e881048ecd1f0b79ddbc8"
      url "https://github.com/AWDDude/ent/releases/download/v#{version}/ent_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7906399e9832c5e8d64ff97745646d7c799c2e6e36c7bb5375ab6e89a049268e"
      url "https://github.com/AWDDude/ent/releases/download/v#{version}/ent_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f63879874e9c1a0a2cebe43b47990df196ca75e1f2493b5ff23d5ea21904b174"
      url "https://github.com/AWDDude/ent/releases/download/v#{version}/ent_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ent"
  desc "A project manager CLI — organise and navigate your projects tree"
  homepage "https://github.com/AWDDude/ent"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ent"

  # No zap stanza required

  caveats <<~EOS
    Add shell integration to your rc file:

      # zsh (~/.zshrc)
      eval "$(ent completion zsh)"

      # bash (~/.bashrc)
      eval "$(ent completion bash)"

      # fish (~/.config/fish/config.fish)
      ent completion fish | source

      # PowerShell ($PROFILE)
      ent completion powershell | Out-String | Invoke-Expression
  EOS
end
