# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Engram < Formula
  desc "MCP server for long-term semantic memory"
  homepage "https://github.com/AWDDude/engRam"
  version "3.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AWDDude/engRam/releases/download/v3.0.0/engram_darwin_amd64.tar.gz"
      sha256 "cba682468f9966de2e58a0d88b02243e28e29c78387f85037badeca6a4d6e087"

      define_method(:install) do
        bin.install "engram"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AWDDude/engRam/releases/download/v3.0.0/engram_darwin_arm64.tar.gz"
      sha256 "e234d940eef3b4c8a243a0e72eba22ebd894474151626807c57d9926b5d360f4"

      define_method(:install) do
        bin.install "engram"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AWDDude/engRam/releases/download/v3.0.0/engram_linux_amd64.tar.gz"
      sha256 "b545d5e31d5df0e704908ef0fe7e506f245efe594abed1940fcfb50543cd419a"
      define_method(:install) do
        bin.install "engram"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AWDDude/engRam/releases/download/v3.0.0/engram_linux_arm64.tar.gz"
      sha256 "1f158aa3eb62829b261918a531b970186d265564c40256bfe798f96c8538bf5e"
      define_method(:install) do
        bin.install "engram"
      end
    end
  end
end
