# This file was generated by GoReleaser. DO NOT EDIT.
cask "ent" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "906b112552fe59bc788205db274f91e727471f63e02f585a7400f07236dce1a9"
      url "https://github.com/AWDDude/ent/releases/download/v#{version}/ent_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6f97fdb3aaf6c5bb1aa112aae820dde335bc7b43630f4bb6649b4c1e45da195a"
      url "https://github.com/AWDDude/ent/releases/download/v#{version}/ent_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b06d227d7fcc7b9111cd1d59304e4f6e3a1c4cbc35fee10979c59803cc1399d2"
      url "https://github.com/AWDDude/ent/releases/download/v#{version}/ent_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1a3c3cd85d3f8dee86e0e38a27caa9b8bddba9b7a3914760739a7d87c5da2536"
      url "https://github.com/AWDDude/ent/releases/download/v#{version}/ent_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ent"
  desc "A project manager CLI — organise and navigate your projects tree"
  homepage "https://github.com/AWDDude/ent"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ent"

  # No zap stanza required

  caveats <<~EOS
    Add shell integration to your rc file:

      # zsh (~/.zshrc)
      eval "$(ent completion zsh)"

      # bash (~/.bashrc)
      eval "$(ent completion bash)"

      # fish (~/.config/fish/config.fish)
      ent completion fish | source

      # PowerShell ($PROFILE)
      ent completion powershell | Out-String | Invoke-Expression
  EOS
end
