# typed: strict
# frozen_string_literal: true

# Generated by `task formula` in github.com/AWDDude/loci. Do not edit.
class Loci < Formula
  desc "Entity-oriented persistent memory MCP server for coding agents"
  homepage "https://github.com/AWDDude/loci"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/AWDDude/loci/releases/download/v0.1.0/loci_darwin_arm64.tar.gz"
      sha256 "b62a36fa4f4a395ce11cf38f8661cc29ca125c77730c09452a052e7f934d9650"
    end
    on_intel do
      url "https://github.com/AWDDude/loci/releases/download/v0.1.0/loci_darwin_amd64.tar.gz"
      sha256 "65f813c4b568cc97ececde29340eac8d19dddb5e6bc70175b755d60f113f8da0"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/AWDDude/loci/releases/download/v0.1.0/loci_linux_arm64.tar.gz"
      sha256 "d7859e27d61295125681fdaa456fc63aa1a872558c91e56e13c4bc2d993d129b"
    end
    on_intel do
      url "https://github.com/AWDDude/loci/releases/download/v0.1.0/loci_linux_amd64.tar.gz"
      sha256 "46042eda50876247111fe93e5c6dd9865999b782eb9a80680776370ea30de6e8"
    end
  end

  def install
    bin.install "loci"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/loci version")
  end
end
